[project]
name = "bioarm-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "grpcio-tools>=1.70.0",
    "grpcio>=1.70.0",
    "protobuf>=5.29.3",
]
